language: ruby
cache:
- bundler
- yarn
before_install:
  - nvm install 12.16
services:
  - postgresql
script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:setup
  - bundle exec rake test
  - bundle exec rake test:system
